- name: Copy oasis
  delegate_to: localhost
  run_once: yes
  copy:
    src: "files/{{ansible_machine}}/oasis/oasis-linux-amd64-{{dbup_version}}.tar.gz"
    dest: /tmp/

- name: Unzip oasis
  delegate_to: localhost
  run_once: yes
  unarchive:
    remote_src: yes
    src: /tmp/oasis-linux-amd64-{{dbup_version}}.tar.gz
    dest: /tmp


- name: Config dbup
  tags: [template]
  delegate_to: localhost
  run_once: yes
  template:
    src: templates/redis-cluster-deploy.conf.template
    dest: /tmp/oasis-linux-amd64/config/redis-cluster-deploy.conf.template

- name: check redis_svc
  shell: "systemctl status redis16579"
  register: svc_redis
  ignore_errors: true

- name: Install redis
  delegate_to: localhost
  run_once: yes
  command:
    cmd: "./dbup redis cluster-deploy -c ../config/redis-cluster-deploy.conf.template"
    chdir: /tmp/oasis-linux-amd64/bin
  when: svc_redis.rc != 0
  ignore_errors: true

- name: Enable redis
  service:
    enabled: yes
    state: started
    name: "redis{{redis_cluster_port}}"
