- name: Copy nignx rpm to remote server
  copy:
    src: files/{{ansible_machine}}/nginx/nginx-1.20.0-1.el7.ngx.x86_64.rpm
    dest: /tmp/

- name: Install nginx rpm
  command: "yum localinstall -y /tmp/nginx-1.20.0-1.el7.ngx.x86_64.rpm"

- name: Config nginx default config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Make folders
  file:
    state: directory
    path: /etc/nginx/certs.d
    owner: nginx
    group: nginx

