- name: Install libgomp 
  include_tasks: "install_libgomp.yaml"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "22"

- name: Define  mode
  set_fact:
    mode: "pseudo"
    use_dbup: true
  when: groups["redisgraph"]|length == 1 and redisgraph_pseudo_mode == "true"

- name: Define standalone mode
  set_fact:
    mode: "standalone"
    use_dbup: true
  when: groups["redisgraph"]|length == 1 and redisgraph_pseudo_mode == "false"

- name: Define master-slave mode
  set_fact:
    mode: "master-slave"
    use_dbup: true
  when: groups["redisgraph"]|length == 2

- name: Define cluster mode
  set_fact:
    mode: "cluster"
    use_dbup: false
  when: groups["redisgraph"]|length > 2

- name: Display mode
  debug:
    msg: "mode: {{mode}}, use_dbup: {{use_dbup}}"

- name: Install pseudo redisgraph
  include_tasks: "dbup_pseudo.yaml"
  when: mode == "pseudo" and use_dbup

- name: Install standalone redisgraph
  include_tasks: "dbup_standalone.yaml"
  when: mode == "standalone" and use_dbup

- name: Install master-slave redisgraph
  include_tasks: "dbup_cluster.yaml"
  when: mode == "master-slave" and use_dbup

- name: Install redisgraph-cluster
  include_tasks: "cluster.yaml"
  when: mode == "cluster"
