- name: Create ingress controller config
  run_once: yes
  delegate_to: "{{groups['k8s_master'][0]}}"
  template:
    src: "templates/ingress.yaml.j2"
    dest: /etc/kubernetes/ingress.yaml

- name: Deploy ingress
  run_once: yes
  become: yes
  delegate_to: "{{groups['k8s_master'][0]}}"
  command: "kubectl apply -f /etc/kubernetes/ingress.yaml"
