- name: Copy oasis
  copy:
    src: "files/{{ansible_machine}}/oasis/oasis-linux-amd64-{{dbup_version}}.tar.gz"
    dest: /tmp/

- name: Unzip oasis
  unarchive:
    remote_src: yes
    src: /tmp/oasis-linux-amd64-{{dbup_version}}.tar.gz
    dest: /tmp

- name: check mongo
  shell : "systemctl status mongodb{{mongo_service_port}} 2>&1 | grep 'not be found' | wc -l"
  register: svc_mongo
  ignore_errors: True

- name: Install mongo
  command:
    cmd: "./dbup mongodb install --port={{mongo_service_port}} --dir={{mongo_install_root}}/mongodb{{mongo_service_port}} --memory={{mongo_service_memory}} --username='{{mongo_service_user}}' --password='{{security['mongo_service_password']}}' --owner='{{hostvars[inventory_hostname].ansible_default_ipv4.address}}' -y"
    chdir: /tmp/oasis-linux-amd64/bin
  when: svc_mongo.stdout == "1"

- name: Enable mongo
  systemd:
    enabled: yes
    state: restarted
    name: "{{item}}"
    daemon_reload: yes
  with_items:
    - "mongodb{{mongo_service_port}}"
  when: dayu_mode != "core"

- name: Disable mongo
  ignore_errors: True
  systemd:
    enabled: false
    state: stopped
    name: "{{item}}"
    daemon_reload: yes
  with_items:
    - "mongodb{{mongo_service_port}}"
  when: dayu_mode == "core"