- name: Define pg_master host group
  add_host:
    groups:
      - pg_master      
    name: "{{item}}"
  when: hostvars[item]['pg_is_master'] == true
  loop: "{{groups['pg']}}"

- name: Define xh_master host group
  add_host:
    groups:
      - xh_master      
    name: "{{item}}"
  when: hostvars[item]['bm_is_master'] == "true"
  loop: "{{groups['xh']}}"
      
- include: fix_drmo.yaml
  when: rg_is_exist == "true"