- name: stop redis svc
  service: name=redis16379 state=stopped
  ignore_errors: true

- name: stop redis svc
  service: name=redis6379 state=stopped
  ignore_errors: true

- name: rm redis svc
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - /usr/lib/systemd/system/redis16379.service
    - /usr/lib/systemd/system/redis6379.service

- name: rm redis data
  file:
    path: /data01/s/services/redis
    state: absent
  ignore_errors: true

- name: daemon svc
  shell: "systemctl daemon-reload"
