- name: echo loki url
  debug: 
    msg: "{{hostvars[inventory_hostname].ansible_default_ipv4.address}}:{{loki_service_port}}"

- name: check loki service
  ignore_errors: true
  shell: "curl {{hostvars[inventory_hostname].ansible_default_ipv4.address}}:{{loki_service_port}}"
  register: loki_svc

- name: echo loki svc result
  debug: 
    msg: "loki svc :{{hostvars[inventory_hostname].ansible_default_ipv4.address}}:{{loki_service_port}} is ok"
  when: loki_svc.rc == 0

- name: echo loki svc result
  debug:
    msg: "loki svc :{{hostvars[inventory_hostname].ansible_default_ipv4.address}}:{{loki_service_port}} not running, now processing install"
  when: loki_svc.rc != 0

- include: loki.yaml
  when: loki_svc.rc != 0


    
