- name: Create minio config
  template: >
    src=templates/minio.env.j2
    dest="{{minio_install_root}}/etc/minio.env"
    mode=0600
    owner={{app_user}}
    group={{app_group}}

- name: Create minio systemd config
  template: >
    src=templates/minio.service.j2
    dest=/etc/systemd/system/minio.service

- name: Start minio
  systemd: >
    name=minio
    state=started
    enabled=yes
    daemon_reload=yes

- name: Wait for minio initialized
  wait_for: >
    timeout=30
