- name: stop redisgraph_exporter svc 
  service: name=redis_exporter9122 state=stopped
  ignore_errors: true

- name: rm redisgraph_exporter svc
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - redis_exporter9122.service

- name: rm redisgraph_exporter svc file
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - "/usr/lib/systemd/system/redis_exporter9122.service"

- name: rm redisgraph_exporter data
  file:
    path: "{{install_redisgraph_exporter_root}}" 
    state: absent
  ignore_errors: true

- name: daemon svc
  shell: "systemctl daemon-reload"

- name: reset failed svc
  shell: "systemctl reset-failed"
